### ISSUE TITLE
Will you update the code for semantic image segmentation next?

### ISSUE THREAD

**Issue by ChaoXiang661** [ChongjianGE/CARE#2]

**Comment by ChongjianGE** [comment]
Hi @ChaoXiang661,

We use the [OpenSelfSup Repo](https://github.com/open-mmlab/OpenSelfSup) for detection and segmentation evaluation. We will release the trained model for the downstream tasks later. Thanks for your interest in our work.

**Comment by KeanuWongves** [comment]
@ChongjianGE Hi，I'm tring to use cnn and transformer within a KL model for semantic segmantion, ur peper enlights me a lot, but I'm still confusing, In semantic segmentation usually uses encode-decode archtecture, so where is the pretext using for, is it between  the encoder and decoder or after the decoder. and what should the predictor like , still the same for classification

**Comment by ChongjianGE** [comment]
Hi @q671383789  ，
This is perhaps a misunderstanding. The pretext is only used for the pretraining purpose. 

After the pretraining stage, we only adopt the pre-trained encoder for the downstream tasks. That's to say, we initialize the CNN encoder (i.e., the ResNet50 backbone without any predictors or projectors) with the pre-trained weight, and attach a new head (i.e., the MaskRCNN head) to the backbone for the semantic segmentation training.

**Comment by KeanuWongves** [comment]
I know that, that's to say ,whether classification or segmentation the pretraining process is the same?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月19日(星期五) 晚上8:15
收件人: ***@***.***&gt;; 
抄送: "系要听Rock &amp; ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ChongjianGE/CARE] Will you update the code for semantic image segmentation next? (Issue #2)





 
Hi @q671383789  ，
 This is perhaps a misunderstanding. The pretext is only used for the pretraining purpose.
 
After the pretraining stage, we only adopt the pre-trained encoder for the downstream tasks. That's to say, we initialize the CNN encoder (i.e., the ResNet5 backbone without any predictors or projectors) with the pre-trained weight, and attach a new head (i.e., the MaskRCNN head) to the backbone for the semantic segmentation training.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ChongjianGE** [comment]
@q671383789 
Exactly.  All the downstream tasks (e.g., classification, detection, and segmentation) share the same pretraining process.

**Comment by ChongjianGE** [comment]
Since there are no further questions, I will close this issue. Please feel free to reopen it when necessary.
